language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "nightly"

# save pip installs between runs
cache: "pip"

matrix:
  fast_finish: true
  allowed_failures:
    - python: "nightly"

# command to install dependencies
install: 
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -U .
script:
  - py.test -v --cov=r4
#  - mypy --ignore-missing-imports --disallow-any expr --disallow-untyped-calls --disallow-untyped-defs r4
  - coverage xml
  - cat coverage.xml
  - codecov -v --required

